# Playing with Normalizing Flows

## Imports

In [99]:
import torch
from flows import RadialFlow, PlanarFlow
from models import FCNEncoder, FCNDecoder, FlowModel

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Unit tests

In [148]:
layer = PlanarFlow(5)

In [149]:
z = torch.FloatTensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
f, log_det = layer(z)

tensor([[ -6.1688],
        [-14.5906]], grad_fn=<UnsqueezeBackward0>)
tensor([[ 0.5134,  2.6061,  3.5839,  3.4757,  5.6268],
        [ 5.5124,  7.6074,  8.5851,  8.4746, 10.6281]], grad_fn=<AddBackward0>)
tensor([[-2.9931e-03,  1.2425e-03,  1.3876e-03,  1.6391e-03, -4.8029e-03],
        [-6.5852e-07,  2.7337e-07,  3.0528e-07,  3.6064e-07, -1.0567e-06]],
       grad_fn=<MulBackward0>)
tensor([8.5175e-04, 2.3842e-07], grad_fn=<LogBackward>)


In [151]:
print(f)
print(log_det)

tensor([[ 0.5134,  2.6061,  3.5839,  3.4757,  5.6268],
        [ 5.5124,  7.6074,  8.5851,  8.4746, 10.6281]], grad_fn=<AddBackward0>)
tensor([8.5175e-04, 2.3842e-07], grad_fn=<LogBackward>)


In [159]:
layer = RadialFlow(5)
z = torch.FloatTensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
f, log_det = layer(z)

In [160]:
print(f)
print(log_det)

tensor([[0.8975, 1.8443, 2.8325, 3.8237, 4.6507],
        [5.5996, 6.5464, 7.5346, 8.5258, 9.3528]], grad_fn=<AddBackward0>)
tensor([nan], grad_fn=<AddBackward0>)
